version: 2.1

jobs:
  tests:
    docker:
      - image: reactnativecommunity/react-native-android:2019-5-29
    environment:
      - TERM: "dumb"
      - ADB_INSTALL_TIMEOUT: 10
      - _JAVA_OPTIONS: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
      - GRADLE_OPTS: '-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs="-XX:+HeapDumpOnOutOfMemoryError"'
      - BUILD_THREADS: 2
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "manifest.gradle" }}-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}-{{ checksum "ipfslite/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "manifest.gradle" }}-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}-{{ checksum "ipfslite/build.gradle" }}
      - run:
          name: Lists installed targets
          command: android list target
          environment:
          TERM: dumb
      - run:
          name: Create emulator
          command: |
            source ".circleci/scripts/.tests.env"
            AVD_PACKAGES="system-images;android-$ANDROID_SDK_TARGET_API_LEVEL;google_apis;$AVD_ABI"
            echo "Creating AVD with packages $AVD_PACKAGES"
            sdkmanager "$AVD_PACKAGES" && echo "no" | avdmanager create avd --name "$AVD_NAME" --force --package "$AVD_PACKAGES" --tag google_apis --abi "$AVD_ABI"
      - run:
          name: Launch emulator
          background: true
          command: |
            source ".circleci/scripts/.tests.env"
            "$ANDROID_HOME/emulator/emulator" -avd "$AVD_NAME" -no-audio -no-window
      - run:
          name: Wait for emulator
          command: |
            source ".circleci/scripts/.tests.env"
            ".circleci/scripts/wait_for_emulator.sh"
      - run:
          name: Run Tests
          command: ./gradlew ipfslite:connectedAndroidTest

workflows:
  version: 2
  android-ipfs-lite:
    jobs:
      - tests

